services:
  backend:
    build:
      context: ./backend/vulnerable
    volumes:
      - ./backend/vulnerable:/app
      - ./database:/app/database
    ports:
      - "8000:8000"  
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"  
    depends_on:
      - backend

